### ISSUE TITLE
activitysteam.ms

### ISSUE THREAD

**Issue by digitalplaywright** [kristianmandrup/authorize-mw#2]
Are you conceptually using the activitysteam.ms as the authorize-mw API convention? If so, it would be really cool to hear your insight on using that convention in this context.

**Comment by digitalplaywright** [comment]
I should probably provide a link to activitysteam.ms http://activitystrea.ms/.

**Comment by kristianmandrup** [comment]
I never heard about http://activitystrea.ms/ but it is pretty logical to use the same conceptual idea for authorization I guess
