### ISSUE TITLE
All javascript says "Generated by LiveScript"

### ISSUE THREAD

**Issue by digitalplaywright** [kristianmandrup/authorize-mw#4]
It seems like your original code in LiveScript is not distributed as part of this project, if so potential contributors can only contribute changes to the generated code. Do you have any plans to release the LiveScript source?

**Comment by kristianmandrup** [comment]
I now added usage examples in Javascript and both the ls and js files should be released.
In the near future I would like to change the class model to use http://jsclass.jcoglan.com/ instead, as it is more compatible with javascript and more powerful in general
